export interface WatchOrderTitle {
  title: string
  year: number
  mediaType?: 'movie' | 'tv'
}

export interface WatchOrder {
  slug: string
  name: string
  tag: string
  description: string
  source?: string
  titles: WatchOrderTitle[]
}

export const WATCH_ORDERS: WatchOrder[] = [
  {
    slug: 'dc-animated-originals',
    name: 'DC Universe Animated Original Movies',
    tag: 'DC · Animated',
    description: 'Release order of the DCUAOM line — standalones, DCAMU, and Tomorrowverse.',
    source: 'https://en.wikipedia.org/wiki/DC_Universe_Animated_Original_Movies',
    titles: [
      { title: 'Superman: Doomsday', year: 2007 },
      { title: 'Justice League: The New Frontier', year: 2008 },
      { title: 'Batman: Gotham Knight', year: 2008 },
      { title: 'Wonder Woman', year: 2009 },
      { title: 'Green Lantern: First Flight', year: 2009 },
      { title: 'Superman/Batman: Public Enemies', year: 2009 },
      { title: 'Justice League: Crisis on Two Earths', year: 2010 },
      { title: 'Batman: Under the Red Hood', year: 2010 },
      { title: 'Superman/Batman: Apocalypse', year: 2010 },
      { title: 'All-Star Superman', year: 2011 },
      { title: 'Green Lantern: Emerald Knights', year: 2011 },
      { title: 'Batman: Year One', year: 2011 },
      { title: 'Justice League: Doom', year: 2012 },
      { title: 'Superman vs. The Elite', year: 2012 },
      { title: 'Batman: The Dark Knight Returns, Part 1', year: 2012 },
      { title: 'Batman: The Dark Knight Returns, Part 2', year: 2013 },
      { title: 'Superman: Unbound', year: 2013 },
      { title: 'Justice League: The Flashpoint Paradox', year: 2013 },
      { title: 'Justice League: War', year: 2014 },
      { title: 'Son of Batman', year: 2014 },
      { title: 'Batman: Assault on Arkham', year: 2014 },
      { title: 'Justice League: Throne of Atlantis', year: 2015 },
      { title: 'Batman vs. Robin', year: 2015 },
      { title: 'Justice League: Gods and Monsters', year: 2015 },
      { title: 'Batman: Bad Blood', year: 2016 },
      { title: 'Justice League vs. Teen Titans', year: 2016 },
      { title: 'Batman: The Killing Joke', year: 2016 },
      { title: 'Justice League Dark', year: 2017 },
      { title: 'Teen Titans: The Judas Contract', year: 2017 },
      { title: 'Batman and Harley Quinn', year: 2017 },
      { title: 'Batman: Gotham by Gaslight', year: 2018 },
      { title: 'Suicide Squad: Hell to Pay', year: 2018 },
      { title: 'The Death of Superman', year: 2018 },
      { title: 'Reign of the Supermen', year: 2019 },
      { title: 'Constantine: City of Demons', year: 2018 },
      { title: 'Justice League vs. the Fatal Five', year: 2019 },
      { title: 'Batman: Hush', year: 2019 },
      { title: 'Wonder Woman: Bloodlines', year: 2019 },
      { title: 'Superman: Red Son', year: 2020 },
      { title: 'Justice League Dark: Apokolips War', year: 2020 },
      { title: 'Superman: Man of Tomorrow', year: 2020 },
      { title: 'Batman: Soul of the Dragon', year: 2021 },
      { title: 'Justice Society: World War II', year: 2021 },
      { title: 'Batman: The Long Halloween, Part One', year: 2021 },
      { title: 'Batman: The Long Halloween, Part Two', year: 2021 },
      { title: 'Injustice', year: 2021 },
      { title: 'Catwoman: Hunted', year: 2022 },
      { title: 'Green Lantern: Beware My Power', year: 2022 },
      { title: 'Batman and Superman: Battle of the Super Sons', year: 2022 },
      { title: 'Legion of Super-Heroes', year: 2023 },
      { title: 'Batman: The Doom That Came to Gotham', year: 2023 },
      { title: 'Justice League: Warworld', year: 2023 },
      { title: 'Justice League: Crisis on Infinite Earths - Part One', year: 2024 },
      { title: 'Justice League: Crisis on Infinite Earths - Part Two', year: 2024 },
      { title: 'Justice League: Crisis on Infinite Earths - Part Three', year: 2024 },
      { title: 'Watchmen Chapter I', year: 2024 },
      { title: 'Watchmen Chapter II', year: 2024 },
    ],
  },
  {
    slug: 'dcamu',
    name: 'DC Animated Movie Universe',
    tag: 'DC · Shared universe',
    description: 'The New 52–inspired shared universe, Flashpoint Paradox through Apokolips War.',
    source: 'https://en.wikipedia.org/wiki/DC_Animated_Movie_Universe',
    titles: [
      { title: 'Justice League: The Flashpoint Paradox', year: 2013 },
      { title: 'Justice League: War', year: 2014 },
      { title: 'Son of Batman', year: 2014 },
      { title: 'Justice League: Throne of Atlantis', year: 2015 },
      { title: 'Batman vs. Robin', year: 2015 },
      { title: 'Batman: Bad Blood', year: 2016 },
      { title: 'Justice League vs. Teen Titans', year: 2016 },
      { title: 'Justice League Dark', year: 2017 },
      { title: 'Teen Titans: The Judas Contract', year: 2017 },
      { title: 'Suicide Squad: Hell to Pay', year: 2018 },
      { title: 'The Death of Superman', year: 2018 },
      { title: 'Reign of the Supermen', year: 2019 },
      { title: 'Constantine: City of Demons', year: 2018 },
      { title: 'Batman: Hush', year: 2019 },
      { title: 'Wonder Woman: Bloodlines', year: 2019 },
      { title: 'Justice League Dark: Apokolips War', year: 2020 },
    ],
  },
  {
    slug: 'mcu-release',
    name: 'MCU — theatrical release order',
    tag: 'Marvel',
    description: 'Marvel Cinematic Universe movies in the order they hit theaters.',
    source: 'https://en.wikipedia.org/wiki/List_of_Marvel_Cinematic_Universe_films',
    titles: [
      { title: 'Iron Man', year: 2008 },
      { title: 'The Incredible Hulk', year: 2008 },
      { title: 'Iron Man 2', year: 2010 },
      { title: 'Thor', year: 2011 },
      { title: 'Captain America: The First Avenger', year: 2011 },
      { title: 'The Avengers', year: 2012 },
      { title: 'Iron Man 3', year: 2013 },
      { title: 'Thor: The Dark World', year: 2013 },
      { title: 'Captain America: The Winter Soldier', year: 2014 },
      { title: 'Guardians of the Galaxy', year: 2014 },
      { title: 'Avengers: Age of Ultron', year: 2015 },
      { title: 'Ant-Man', year: 2015 },
      { title: 'Captain America: Civil War', year: 2016 },
      { title: 'Doctor Strange', year: 2016 },
      { title: 'Guardians of the Galaxy Vol. 2', year: 2017 },
      { title: 'Spider-Man: Homecoming', year: 2017 },
      { title: 'Thor: Ragnarok', year: 2017 },
      { title: 'Black Panther', year: 2018 },
      { title: 'Avengers: Infinity War', year: 2018 },
      { title: 'Ant-Man and the Wasp', year: 2018 },
      { title: 'Captain Marvel', year: 2019 },
      { title: 'Avengers: Endgame', year: 2019 },
      { title: 'Spider-Man: Far From Home', year: 2019 },
      { title: 'Black Widow', year: 2021 },
      { title: 'Shang-Chi and the Legend of the Ten Rings', year: 2021 },
      { title: 'Eternals', year: 2021 },
      { title: 'Spider-Man: No Way Home', year: 2021 },
      { title: 'Doctor Strange in the Multiverse of Madness', year: 2022 },
      { title: 'Thor: Love and Thunder', year: 2022 },
      { title: 'Black Panther: Wakanda Forever', year: 2022 },
      { title: 'Ant-Man and the Wasp: Quantumania', year: 2023 },
      { title: 'Guardians of the Galaxy Vol. 3', year: 2023 },
      { title: 'The Marvels', year: 2023 },
      { title: 'Deadpool & Wolverine', year: 2024 },
      { title: 'Captain America: Brave New World', year: 2025 },
      { title: 'Thunderbolts*', year: 2025 },
      { title: 'The Fantastic Four: First Steps', year: 2025 },
    ],
  },
  {
    slug: 'dceu-release',
    name: 'DCEU — theatrical release order',
    tag: 'DC · Live action',
    description: 'DC Extended Universe movies in the order they hit theaters, including Snyder Cut.',
    source: 'https://en.wikipedia.org/wiki/DC_Extended_Universe',
    titles: [
      { title: 'Man of Steel', year: 2013 },
      { title: 'Batman v Superman: Dawn of Justice', year: 2016 },
      { title: 'Suicide Squad', year: 2016 },
      { title: 'Wonder Woman', year: 2017 },
      { title: 'Justice League', year: 2017 },
      { title: 'Aquaman', year: 2018 },
      { title: 'Shazam!', year: 2019 },
      { title: 'Birds of Prey', year: 2020 },
      { title: 'Wonder Woman 1984', year: 2020 },
      { title: "Zack Snyder's Justice League", year: 2021 },
      { title: 'The Suicide Squad', year: 2021 },
      { title: 'Black Adam', year: 2022 },
      { title: 'Shazam! Fury of the Gods', year: 2023 },
      { title: 'The Flash', year: 2023 },
      { title: 'Blue Beetle', year: 2023 },
      { title: 'Aquaman and the Lost Kingdom', year: 2023 },
    ],
  },
]

export function watchOrderSummaries() {
  return WATCH_ORDERS.map(order => ({
    slug: order.slug,
    name: order.name,
    tag: order.tag,
    description: order.description,
    source: order.source,
    count: order.titles.length,
  }))
}

export function findWatchOrder(slug: string) {
  return WATCH_ORDERS.find(order => order.slug === slug) ?? null
}
